export const mapping = [
    [
        "graphicinfobin:",
        "graphicbin:",
        /bin\\GraphicInfo_(\d+).bin$/i,
        /bin\\Graphic_(\d+).bin$/i,
    ],
    [
        "graphicinfobinex:",
        "graphicbinex:",
        /bin\\GraphicInfoEx_(\d+).bin$/i,
        /bin\\GraphicEx_(\d+).bin$/i,
    ],
    [
        "graphicinfobinv1:",
        "graphicbinv1:",
        /bin\\GraphicInfoV1_(\d+).bin$/i,
        /bin\\GraphicV1_(\d+).bin$/i,
    ],
    [
        "graphicinfobinv2:",
        "graphicbinv2:",
        /bin\\GraphicInfoV2_(\d+).bin$/i,
        /bin\\GraphicV2_(\d+).bin$/i,
    ],
    [
        "graphicinfobinv3:",
        "graphicbinv3:",
        /bin\\GraphicInfoV3_(\d+).bin$/i,
        /bin\\GraphicV3_(\d+).bin$/i,
    ],
    [
        "graphicinfobin_puk1:",
        "graphicbin_puk1:",
        /bin\\PUK1\\GraphicInfo_PUK1_(\d+).bin$/i,
        /bin\\PUK1\\Graphic_PUK1_(\d+).bin$/i,
    ],
    ...[1, 2, 3, 4, 5, 6, 7, 8, 9].map(e => [
        `graphicinfobin_puk${e}:`,
        `graphicbin_puk${e}:`,
        new RegExp(`bin\\\\PUK${e}\\\\GraphicInfo_PUK${e}_(\\d+).bin$`, 'i'),
        new RegExp(`bin\\\\PUK${e}\\\\Graphic_PUK${e}_(\\d+).bin$`, 'i'),
    ]),
    ...[1, 2, 3, 4, 5, 6, 7, 8, 9].map(e => [
        `animeinfobin_puk${e}:`,
        `animebin_puk${e}:`,
        new RegExp(`bin\\\\PUK${e}\\\\AnimeInfo_PUK${e}_(\\d+).bin$`, 'i'),
        new RegExp(`bin\\\\PUK${e}\\\\Anime_PUK${e}_(\\d+).bin$`, 'i'),
    ]),
    [
        "graphicinfobin_joy:",
        "graphicbin_joy:",
        /bin\\GraphicInfo_joy_(\d+).bin$/i,
        /bin\\Graphic_joy_(\d+).bin$/i,
    ],
    [
        "graphicinfobin_joy_ex:",
        "graphicbin_joy_ex:",
        /bin\\GraphicInfo_joy_EX_(\d+).bin$/i,
        /bin\\Graphic_joy_EX_(\d+).bin$/i,
    ],
    ...[1, 2, 3, 4, 5, 6, 7, 8, 9].map(e => [
        `graphicinfobin_exp${e}:`,
        `graphicbin_exp${e}:`,
        new RegExp(`bin\\\\cgmsv\\\\GraphicInfo_EXP${e}_(\\d+).bin$`, 'i'),
        new RegExp(`bin\\\\cgmsv\\\\Graphic_EXP${e}_(\\d+).bin$`, 'i'),
    ]),
    ...[1, 2, 3, 4, 5, 6, 7, 8, 9].map(e => [
        `animeinfobin_exp${e}:`,
        `animebin_exp${e}:`,
        new RegExp(`bin\\\\cgmsv\\\\AnimeInfo_EXP${e}_(\\d+).bin$`, 'i'),
        new RegExp(`bin\\\\cgmsv\\\\Anime_EXP${e}_(\\d+).bin$`, 'i'),
    ]),
    [
        "graphicinfobin_joy_ch:",
        "graphicbin_joy_ch:",
        /bin\\GraphicInfo_JOY_CH(\d+).bin$/i,
        /bin\\Graphic_JOY_CH(\d+).bin$/i,
    ],
    [
        "coordinatebinv3:",
        "coordinateinfobinv3:",
        /bin\\coordinatev3_(\d+).bin$/i,
        /bin\\coordinateinfov3_(\d+).bin$/i,
    ],
    [
        "animebin:",
        "animeinfobin:",
        /bin\\Anime_(\d+).bin$/i,
        /bin\\AnimeInfo_(\d+).bin$/i,
    ],
    [
        "animebinex:",
        "animeinfobinex:",
        /bin\\AnimeEx_(\d+).bin$/i,
        /bin\\AnimeInfoEx_(\d+).bin$/i,
    ],
    [
        "animebinex:",
        "animeinfobinex:",
        /bin\\AnimeEx_(\d+).bin$/i,
        /bin\\AnimeInfoEx_(\d+).bin$/i,
    ],
    [
        "animebinv3:",
        "animeinfobinv3:",
        /bin\\AnimeV3_(\d+).bin$/i,
        /bin\\AnimeInfoV3_(\d+).bin$/i,
    ],
    [
        "animebin_joy:",
        "animeinfobin_joy:",
        /bin\\Anime_Joy_(\d+).bin$/i,
        /bin\\AnimeInfo_Joy_(\d+).bin$/i,
    ],
    [
        "animebin_joy_ex:",
        "animeinfobin_joy_ex:",
        /bin\\Anime_Joy_EX_(\d+).bin$/i,
        /bin\\AnimeInfo_Joy_EX_(\d+).bin$/i,
    ],
    [
        "animebin_joy_ch:",
        "animeinfobin_joy_ch:",
        /bin\\Anime_Joy_CH(\d+).bin$/i,
        /bin\\AnimeInfo_Joy_CH(\d+).bin$/i,
    ],
]